apiVersion: v1
data:
  .dockerconfigjson: ${DOCKER_REGISTRY_K8S_CREDENTIALS}
kind: Secret
metadata:
  name: docker-registry-credentials
  namespace: ${K8S_NAMESPACE}
type: kubernetes.io/dockerconfigjson